# Generated by Django 6.0.6 on 2026-06-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='application',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='application',
            name='support_market',
        ),
        migrations.RemoveField(
            model_name='application',
            name='support_mentor',
        ),
        migrations.RemoveField(
            model_name='application',
            name='support_money',
        ),
        migrations.RemoveField(
            model_name='application',
            name='support_other',
        ),
        migrations.RemoveField(
            model_name='application',
            name='support_other_text',
        ),
        migrations.AddField(
            model_name='application',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='building_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='other_service',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='services_required',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='founder_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='problem_statement',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='solution',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='startup_name',
            field=models.CharField(max_length=30),
        ),
    ]
