# Generated by Django 6.0.6 on 2026-06-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_address_remove_application_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='building_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='application',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
