# Generated by Django 6.0.6 on 2026-06-18 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_building_name_and_more'),
        ('mentors', '0002_rename_active_mentor_is_active_mentor_mentor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMentorshipReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('review_date', models.DateField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_reviews', to='applications.application')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentors.mentor')),
            ],
            options={
                'db_table': 'application_mentor_reviews',
            },
        ),
    ]
