# Generated by Django 6.0.6 on 2026-06-17 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('startups', '0006_startupemployee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_date',
            new_name='issued_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='description',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='reference',
            new_name='transaction_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='recorded_by',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Card', 'Card'), ('Cash', 'Cash')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='invoice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('AIC-CIIC', 'AIC-CIIC'), ('Mentor', 'Mentor'), ('Startup', 'Startup')], max_length=20)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active', models.BooleanField(default=True)),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startups.startup')),
            ],
        ),
    ]
