# Generated by Django 6.0.6 on 2026-06-18 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_invoice_options_alter_payment_options_and_more'),
        ('startups', '0007_quarterlyfinancialupdate_remindertracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupBillingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active', models.BooleanField(default=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_plan', to='startups.startup')),
            ],
            options={
                'db_table': 'startup_billing_plans',
            },
        ),
    ]
