# Generated by Django 6.0.6 on 2026-06-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentors', '0001_initial'),
        ('startups', '0006_startupemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='mentors.mentor')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_bookings', to='startups.startup')),
            ],
            options={
                'db_table': 'mentorship_bookings',
            },
        ),
    ]
