# Generated by Django 6.0.6 on 2026-06-04 10:37

import django.db.models.deletion
import startups.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_code', models.CharField(default=startups.models.generate_startup_code, max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('virtual', 'Virtual'), ('on-site', 'On-site')], default='on-site', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='startups/logos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('incubated', 'Incubated'), ('graduated', 'Graduated')], default='active', max_length=20)),
                ('profile_complete', models.BooleanField(default=False)),
                ('funding_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valuation', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('incubation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'startups',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='startups/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='startups.startup')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StartupMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='startups/media/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='startups.startup')),
            ],
            options={
                'db_table': 'startup_media',
            },
        ),
        migrations.CreateModel(
            name='StartupTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='startups/team/')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='startups.startup')),
            ],
            options={
                'db_table': 'startup_team_members',
            },
        ),
    ]
