# Generated by Django 6.0.6 on 2026-06-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startup',
            options={'ordering': ['brand_name']},
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='description',
            new_name='company_description',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='company_name',
            new_name='brand_name',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='address',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='email',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='funding_total',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='incubation_year',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='profile_complete',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='status',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='type',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='valuation',
        ),
        migrations.AddField(
            model_name='startup',
            name='cin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='startup',
            name='dpiit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='startup',
            name='funding_stage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='gst_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='startup',
            name='incubation_type',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('residential', 'Residential')], default='virtual', max_length=20),
        ),
        migrations.AddField(
            model_name='startup',
            name='jobs_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='legal_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='market_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='office_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='startup',
            name='office_room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='startup',
            name='onboarding_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='operation_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='pan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='startup',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='revenue_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='sales_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='startup',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='startup_readiness_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='startup_status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('dropped', 'Dropped')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='startup',
            name='startup_valuation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='startup',
            name='sub_sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='trl_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
