# Generated by Django 6.0.6 on 2026-06-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_alter_startup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.URLField(blank=True)),
                ('is_primary_poc', models.BooleanField(default=False)),
                ('is_secondary_poc', models.BooleanField(default=False)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='startups.startup')),
            ],
            options={
                'db_table': 'startup_founders',
            },
        ),
    ]
