# Generated by Django 6.0.6 on 2026-06-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_alter_startup_brand_name_founder'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Website', 'Website'), ('LinkedIn', 'LinkedIn'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube'), ('Other', 'Other')], max_length=50)),
                ('url', models.URLField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='startups.startup')),
            ],
            options={
                'db_table': 'startup_social_media',
            },
        ),
    ]
