# Generated by Django 6.0.6 on 2026-06-17 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_startupsocialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='startups.startup')),
            ],
            options={
                'db_table': 'startup_awards',
            },
        ),
        migrations.CreateModel(
            name='StartupBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('ifsc', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=255)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='startups.startup')),
            ],
            options={
                'db_table': 'startup_bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='StartupFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=20)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valuation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('jobs_created', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='startups.startup')),
            ],
            options={
                'db_table': 'startup_financials',
            },
        ),
        migrations.CreateModel(
            name='StartupFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_type', models.CharField(choices=[('Government Grant', 'Government Grant'), ('Seed Fund', 'Seed Fund'), ('Angel Investment', 'Angel Investment'), ('VC Investment', 'VC Investment'), ('CSR Grant', 'CSR Grant'), ('Debt Funding', 'Debt Funding'), ('Other', 'Other')], max_length=100)),
                ('investor', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('funding_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_records', to='startups.startup')),
            ],
            options={
                'db_table': 'startup_funding',
            },
        ),
        migrations.CreateModel(
            name='StartupIPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipr_type', models.CharField(choices=[('Patent', 'Patent'), ('Trademark', 'Trademark'), ('Copyright', 'Copyright'), ('Design Right', 'Design Right'), ('Trade Secret', 'Trade Secret')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('application_number', models.CharField(blank=True, max_length=100)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iprs', to='startups.startup')),
            ],
            options={
                'db_table': 'startup_ipr',
            },
        ),
        migrations.CreateModel(
            name='StartupLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('loan_date', models.DateField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='startups.startup')),
            ],
            options={
                'db_table': 'startup_loans',
            },
        ),
    ]
