# Generated by Django 6.0.6 on 2026-06-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_startupaward_startupbankaccount_startupfinancial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('compensation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='startups.startup')),
            ],
            options={
                'db_table': 'startup_employees',
            },
        ),
    ]
