# Generated by Django 6.0.6 on 2026-06-18 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_startupemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyFinancialUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=20)),
                ('financial_year', models.CharField(max_length=20)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valuation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('jobs_created', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_updates', to='startups.startup')),
            ],
            options={
                'db_table': 'quarterly_financial_updates',
            },
        ),
        migrations.CreateModel(
            name='ReminderTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('Quarterly Update', 'Quarterly Update'), ('Invoice Payment', 'Invoice Payment'), ('Profile Update', 'Profile Update')], max_length=100)),
                ('due_date', models.DateField()),
                ('reminder_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startup')),
            ],
            options={
                'db_table': 'reminder_tracker',
            },
        ),
    ]
