# Generated by Django 6.0.6 on 2026-06-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0007_quarterlyfinancialupdate_remindertracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='startup',
            name='primary_poc_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='startup',
            name='primary_poc_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='startup',
            name='primary_poc_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='startup',
            name='risk_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='secondary_poc_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='startup',
            name='secondary_poc_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='startup',
            name='secondary_poc_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
