# Generated by Django 6.0.6 on 2026-06-18 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('mentors', '0002_rename_active_mentor_is_active_mentor_mentor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='mentors.mentor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('startup', 'Startup User'), ('mentor', 'Mentor')], default='startup', max_length=20),
        ),
    ]
