# Generated by Django 6.0.6 on 2026-06-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_mentor_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('startup', 'Startup User'), ('mentor', 'Mentor'), ('applicant', 'Applicant')], default='startup', max_length=20),
        ),
    ]
