# Generated by Django 6.0.6 on 2026-06-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=255)),
                ('expertise', models.CharField(max_length=255)),
                ('mentor_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=20)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
