# Generated by Django 6.0.6 on 2026-06-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
