# Generated by Django 6.0.6 on 2026-06-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
        ('startups', '0006_startupemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallbooking',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_bookings', to='startups.startup'),
        ),
    ]
