# Generated by Django 6.0.6 on 2026-06-18 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_alter_hallbooking_startup'),
        ('startups', '0008_startup_keywords_startup_primary_poc_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=255)),
                ('hall_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hallbooking',
            name='attendees',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hallbooking',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hallbooking',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_hall_bookings', to='startups.startup'),
        ),
        migrations.AlterField(
            model_name='hallbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='hallbooking',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='halls.hall'),
        ),
        migrations.DeleteModel(
            name='ConferenceHall',
        ),
    ]
