# Generated by Django 6.0.6 on 2026-06-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=255)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'equipment',
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'labs',
                'db_table': 'labs',
            },
        ),
        migrations.CreateModel(
            name='BookingEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.equipment')),
            ],
            options={
                'db_table': 'booking_equipment',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='labs.lab'),
        ),
        migrations.CreateModel(
            name='LabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment_required', models.ManyToManyField(related_name='bookings', through='labs.BookingEquipment', to='labs.equipment')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='labs.lab')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_bookings', to='startups.startup')),
            ],
            options={
                'db_table': 'lab_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bookingequipment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.labbooking'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingequipment',
            unique_together={('booking', 'equipment')},
        ),
    ]
