# Generated by Django 6.0.6 on 2026-06-17 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={},
        ),
        migrations.AlterModelOptions(
            name='labbooking',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='bookingequipment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='labbooking',
            name='equipment_required',
        ),
        migrations.AddField(
            model_name='bookingequipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookingequipment',
            name='tariff_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='equipment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tariff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lab',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='tariff_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookingequipment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='labs.labbooking'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='EquipmentImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='labs/imports/')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equipment_import_logs',
            },
        ),
    ]
