# Generated by Django 6.0.6 on 2026-06-18 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_startupbillingplan'),
        ('labs', '0002_alter_equipment_options_alter_lab_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='booking_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='invoice_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='startup_members',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='LabTariffTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hourly_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.lab')),
            ],
            options={
                'db_table': 'lab_tariff_templates',
            },
        ),
    ]
