# Generated by Django 6.0.6 on 2026-06-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_equipment_description_lab_lab_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_centre', models.CharField(max_length=255)),
                ('pan_number', models.CharField(blank=True, max_length=50)),
                ('equipment_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('procurement_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'equipment_master',
            },
        ),
    ]
